(()=>{'use strict';
const $=s=>document.querySelector(s),params=new URLSearchParams(location.search),hostMode=params.get('host')==='1',room=params.get('room');
if(hostMode){$('#host').classList.remove('hidden');initHost()}else if(room){$('#controller').classList.remove('hidden');initController(room)}else $('#landing').classList.remove('hidden');
function initHost(){
 const canvas=$('#game'),ctx=canvas.getContext('2d'),lobby=$('#lobby'),roster=$('#roster'),players=new Map();let peer,started=false,gameOver=false,wave=0,farmHp=100,shots=[],beams=[],enemyBeams=[],fireballs=[],enemies=[],drops=[],last=performance.now(),spawn=0,remainingToSpawn=0,bossesToSpawn=0,spawnGroups=[],countdown=0,audio=null,soundOn=false,lastShotSound=0,henLastHit=0,lastHenCry=0,camera={x:900,y:650,scale:.5};
 const world={w:1800,h:1200,home:{x:900,y:650}},trees=[];let enemyGrid=new Map();const assetStatus=$('#assetLoadStatus'),startButton=$('#startBtn'),natureAtlas=new Image(),floorTile=new Image(),soilSprite=new Image(),shackSprite=new Image(),grassClump=new Image(),eggSprite=new Image(),actorSprites={player:new Image(),mama:new Image(),BOSS:new Image(),EAGLE:new Image(),FOX:new Image(),SNAKE:new Image(),WOLF:new Image(),MOLE:new Image(),TORNADO:new Image(),ALIEN:new Image(),MAGE:new Image(),GHOST:new Image(),PLANT:new Image()};let assetsReady=false,assetsPending=19,assetFailures=0,floorPattern=null,mapScene=null;const obstacleCell=240,obstacleGrid=new Map();startButton.disabled=true;assetStatus.textContent='Loading map and character assets…';function assetFinished(ok){if(!ok)assetFailures++;if(--assetsPending<=0){assetsReady=true;mapScene=buildStaticMap();assetStatus.textContent=assetFailures?'Some art did not load; fallback scenery is active.':'Map, farm and character assets ready.';startButton.disabled=false}}for(const [img,path] of [[natureAtlas,'forest-sprites.svg'],[floorTile,'floor-grass-tile.png'],[soilSprite,'fertile-soil.svg'],[shackSprite,'mama-hen-shack.svg'],[grassClump,'grass-clump.svg'],[eggSprite,'mama-egg.svg']]){img.onload=()=>{if(img===floorTile)floorPattern=ctx.createPattern(floorTile,'repeat');assetFinished(true)};img.onerror=()=>assetFinished(false);const url=new URL('./assets/nature/'+path,location.href);url.searchParams.set('v','4');img.src=url.href}for(const [key,file] of [['player','player-chicken.svg'],['mama','mama-hen.svg'],['BOSS','chupacabras.svg'],['EAGLE','eagle.svg'],['FOX','fox.svg'],['SNAKE','snake.svg'],['WOLF','wolf.svg'],['MOLE','mole.svg'],['TORNADO','tornado.svg'],['ALIEN','alien.svg'],['MAGE','mage.svg'],['GHOST','ghost.svg'],['PLANT','plant.svg']]){const img=actorSprites[key];img.onload=()=>assetFinished(true);img.onerror=()=>assetFinished(false);const url=new URL('./assets/actors/'+file,location.href);url.searchParams.set('v','5');img.src=url.href}
 for(let i=0;i<13;i++){const a=i*2.399,r=(760+(i%5)*185)*.5,model=i%8,s=(30+(i*17%25))*.5;trees.push({x:world.home.x+Math.cos(a)*r,y:world.home.y+Math.sin(a)*r,s,model,radius:(model<4?Math.max(5.5,s*.19):model<6?Math.max(8,s*.72):Math.max(4,s*.24))})}
 for(let i=0;i<5;i++){const model=(i*3+1)%8,s=(24+(i*13%27))*.5,x=(150+(i*719%3300))*.5,y=(150+(i*431%2100))*.5;if(Math.abs(x-world.home.x)>125&&Math.abs(y-world.home.y)>112)trees.push({x,y,s,model,radius:(model<4?Math.max(5.5,s*.19):model<6?Math.max(8,s*.72):Math.max(4,s*.24))})}
 const grassTufts=[];for(let i=0;i<20;i++){const x=(100+(i*617%3400))*.5,y=(100+(i*353%2200))*.5;if(Math.abs(x-900)>90&&Math.abs(y-647)>85&&Math.hypot(x-900,y-650)>170)grassTufts.push({x,y,s:(34+(i*13%24))*.5,r:(i*1.71)%6.28})}
 for(const t of trees){const key=Math.floor(t.x/obstacleCell)+','+Math.floor(t.y/obstacleCell),bucket=obstacleGrid.get(key)||[];bucket.push(t);obstacleGrid.set(key,bucket)}
 function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio}addEventListener('resize',resize);resize();
 function send(p){try{p.conn.send({type:'state',x:p.x,y:p.y,aim:p.aim,started})}catch{}}
 function rosterUpdate(){$('#playerCount').textContent=players.size;roster.innerHTML='';for(const p of players.values()){const e=document.createElement('span');e.textContent='🐥 '+p.name;roster.append(e)}}
 const scoreKey='chicken-horde-high-scores-v1';
 function readScores(){try{const v=JSON.parse(localStorage.getItem(scoreKey)||'[]');return Array.isArray(v)?v:[]}catch{return []}}
 function renderScores(target){const list=readScores().sort((a,b)=>b.score-a.score).slice(0,10);target.innerHTML=list.length?'<table class="score-table"><thead><tr><th>#</th><th>PLAYER</th><th>BEST</th><th>WAVE</th></tr></thead><tbody>'+list.map((s,i)=>`<tr><td>${i+1}</td><td>${escapeText(s.name)}</td><td>${s.score}</td><td>${s.wave}</td></tr>`).join('')+'</tbody></table>':'<p class="empty-scores">No scores yet. Start a game!</p>'}
 function escapeText(s){const el=document.createElement('span');el.textContent=String(s);return el.innerHTML}
 function refreshScoreboards(){renderScores($('#lobbyScores'));renderScores($('#finalScores'))}
 function saveRun(){const scores=readScores();for(const p of players.values()){const key=p.name.trim().toUpperCase(),row=scores.find(s=>s.key===key);if(row){if(p.score>row.score){row.score=p.score;row.wave=wave}row.kills=Math.max(row.kills||0,p.kills)}else scores.push({key,name:p.name,score:p.score,wave,kills:p.kills})}scores.sort((a,b)=>b.score-a.score);try{localStorage.setItem(scoreKey,JSON.stringify(scores.slice(0,100)))}catch{}$('#runSummary').textContent=`The farm fell in wave ${wave}. Farm health: ${Math.ceil(farmHp)}%.`;$('#runScores').innerHTML='<table class="score-table"><thead><tr><th>PLAYER</th><th>SCORE</th><th>KILLS</th></tr></thead><tbody>'+[...players.values()].sort((a,b)=>b.score-a.score).map(p=>`<tr><td>${escapeText(p.name)}</td><td>${p.score}</td><td>${p.kills}</td></tr>`).join('')+'</tbody></table>';refreshScoreboards();$('#gameOver').classList.remove('hidden')}
 function screenVectorToWorld(x,y){return {x,y:y/.82}}
 function screenAngleToWorld(a){const v=screenVectorToWorld(Math.cos(a),Math.sin(a));return Math.atan2(v.y,v.x)}
 function addPlayer(conn,msg){if(!msg||msg.type!=='join'||players.has(conn.peer))return;const n=players.size,p={id:conn.peer,name:String(msg.name||'CHICK').slice(0,12),x:world.home.x-75+(n%4)*50,y:world.home.y+90+Math.floor(n/4)*38,aim:0,move:{x:0,y:0},fire:false,hp:100,effects:{},score:0,kills:0,lastHit:0,conn,color:['#ffe05e','#f48caa','#82c9ff','#bd9aff','#77df98','#ffad59'][n%6]};players.set(p.id,p);rosterUpdate();conn.on('data',d=>{if(d.type==='input'){p.move=screenVectorToWorld(d.move?.x||0,d.move?.y||0);p.aim=screenAngleToWorld(d.aim??0);p.fire=!!d.fire}});conn.on('close',()=>{players.delete(p.id);rosterUpdate()});send(p)}
 peer=new Peer(undefined,{debug:0});peer.on('open',id=>{const u=new URL(location.href);u.search='?room='+encodeURIComponent(id);$('#roomCode').textContent=id;$('#joinUrl').textContent=u.href;$('#qr').src='https://api.qrserver.com/v1/create-qr-code/?size=180x180&data='+encodeURIComponent(u.href)});peer.on('connection',conn=>conn.on('data',d=>{if(d.type==='join')addPlayer(conn,d)}));peer.on('error',e=>toast('Connection service: '+e.type));
 $('#startBtn').onclick=()=>{if(started)return;lobby.classList.add('hidden');$('#startBtn').disabled=true;startWave(1)};
 $('#playAgain').onclick=()=>location.reload();refreshScoreboards();
 function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
 function tone(freq=440,duration=.1,type='sine',volume=.035){if(!soundOn||!audio)return;try{const o=audio.createOscillator(),g=audio.createGain(),now=audio.currentTime;o.type=type;o.frequency.setValueAtTime(freq,now);g.gain.setValueAtTime(Math.min(.15,volume*2.2),now);g.gain.exponentialRampToValueAtTime(.001,now+duration);o.connect(g);g.connect(audio.destination);o.start(now);o.stop(now+duration)}catch{}}
 function henCry(){if(!soundOn||!audio)return;try{const now=audio.currentTime,o=audio.createOscillator(),g=audio.createGain();o.type='sawtooth';o.frequency.setValueAtTime(720,now);o.frequency.exponentialRampToValueAtTime(1180,now+.08);o.frequency.exponentialRampToValueAtTime(560,now+.2);o.frequency.exponentialRampToValueAtTime(860,now+.28);o.frequency.exponentialRampToValueAtTime(430,now+.46);g.gain.setValueAtTime(.001,now);g.gain.linearRampToValueAtTime(.045,now+.035);g.gain.setValueAtTime(.04,now+.24);g.gain.exponentialRampToValueAtTime(.001,now+.48);o.connect(g);g.connect(audio.destination);o.start(now);o.stop(now+.49)}catch{}}
 $('#soundBtn').onclick=async()=>{soundOn=!soundOn;if(soundOn){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio){soundOn=false;toast('Audio is not supported in this browser')}else{audio=audio||new Audio();if(audio.state==='suspended')await audio.resume()}}$('#soundBtn').textContent=soundOn?'SOUND ON':'SOUND OFF';tone(620,.12,'triangle')};
 function uprightAt(x,y,draw){ctx.save();ctx.translate(x,y);ctx.transform(1,0,0,1/.82,0,0);draw();ctx.restore()}
 function roundedPath(x,y,w,h,r,c=ctx){const k=Math.min(r,w/2,h/2);c.beginPath();c.moveTo(x+k,y);c.lineTo(x+w-k,y);c.quadraticCurveTo(x+w,y,x+w,y+k);c.lineTo(x+w,y+h-k);c.quadraticCurveTo(x+w,y+h,x+w-k,y+h);c.lineTo(x+k,y+h);c.quadraticCurveTo(x,y+h,x,y+h-k);c.lineTo(x,y+k);c.quadraticCurveTo(x,y,x+k,y);c.closePath()}
 function collidesTree(x,y,r){const gx=Math.floor(x/obstacleCell),gy=Math.floor(y/obstacleCell),reach=Math.ceil((r+90)/obstacleCell);for(let cx=gx-reach;cx<=gx+reach;cx++)for(let cy=gy-reach;cy<=gy+reach;cy++)for(const t of obstacleGrid.get(cx+','+cy)||[])if(Math.hypot(x-t.x,y-t.y)<(t.radius||t.s)+r+6)return true;return false}
 function pathBlocked(x,y,nx,ny,r){const steps=Math.max(1,Math.ceil(Math.hypot(nx-x,ny-y)/8));for(let i=1;i<=steps;i++){const f=i/steps;if(collidesTree(x+(nx-x)*f,y+(ny-y)*f,r))return true}return false}
 function moveCircle(o,dx,dy,r){const count=Math.max(1,Math.ceil(Math.hypot(dx,dy)/8)),sx=dx/count,sy=dy/count;let x=o.x,y=o.y;for(let i=0;i<count;i++){const nx=Math.max(r,Math.min(world.w-r,x+sx));if(!collidesTree(nx,y,r))x=nx;const ny=Math.max(r,Math.min(world.h-r,y+sy));if(!collidesTree(x,ny,r))y=ny}return {x,y}}
 function findSpawnPosition(radius){for(let attempt=0;attempt<32;attempt++){const side=Math.floor(Math.random()*4),x=side===0?90:side===1?world.w-90:Math.random()*world.w,y=side===2?90:side===3?world.h-90:Math.random()*world.h;if(!collidesTree(x,y,radius))return {x,y}}return {x:world.home.x+650,y:world.home.y+500}}
 function moveEnemy(e,dx,dy,r){const clamp=(v,max)=>Math.max(r,Math.min(max-r,v)),x=clamp(e.x+dx,world.w),y=clamp(e.y+dy,world.h);if(!pathBlocked(e.x,e.y,x,y,r)){e.routeAngle=null;e.stuck=0;return {x,y}}const base=Math.atan2(dy,dx),turns=[0,-.42,.42,-.82,.82,-1.25,1.25,-1.72,1.72,-2.35,2.35,Math.PI],step=Math.max(12,Math.hypot(dx,dy));let best=null,bestScore=-Infinity;for(const turn of turns){const a=base+turn,ux=Math.cos(a),uy=Math.sin(a),nx=clamp(e.x+ux*step,world.w),ny=clamp(e.y+uy*step,world.h);if(pathBlocked(e.x,e.y,nx,ny,r))continue;let open=0;for(const ahead of [24,52])if(!collidesTree(clamp(nx+ux*ahead,world.w),clamp(ny+uy*ahead,world.h),r))open++;const score=Math.cos(turn)+open*.13+(e.routeAngle==null?0:Math.cos(a-e.routeAngle)*.16);if(score>bestScore){bestScore=score;best={x:nx,y:ny,angle:a}}}if(!best){e.stuck=(e.stuck||0)+1;if(e.stuck>20){const obstacle=trees.reduce((a,t)=>!a||Math.hypot(t.x-e.x,t.y-e.y)<Math.hypot(a.x-e.x,a.y-e.y)?t:a,null);if(obstacle){const away=Math.atan2(e.y-obstacle.y,e.x-obstacle.x);for(const turn of [0,.7,-.7,1.4,-1.4,2.1,-2.1,Math.PI]){const a=away+turn,nx=clamp(obstacle.x+Math.cos(a)*((obstacle.radius||obstacle.s)+r+10),world.w),ny=clamp(obstacle.y+Math.sin(a)*((obstacle.radius||obstacle.s)+r+10),world.h);if(!collidesTree(nx,ny,r)){e.stuck=0;e.routeAngle=a;return {x:nx,y:ny}}}}}return {x:e.x,y:e.y}}e.stuck=0;e.routeAngle=best.angle;return best}
 function buildEnemyGrid(){enemyGrid.clear();for(const e of enemies){const key=Math.floor(e.x/240)+','+Math.floor(e.y/240),bucket=enemyGrid.get(key)||[];bucket.push(e);enemyGrid.set(key,bucket)}}
 function nearbyEnemies(e,radius){const out=[],gx=Math.floor(e.x/240),gy=Math.floor(e.y/240),reach=Math.ceil(radius/240);for(let x=gx-reach;x<=gx+reach;x++)for(let y=gy-reach;y<=gy+reach;y++)for(const o of enemyGrid.get(x+','+y)||[])if(o!==e&&Math.hypot(o.x-e.x,o.y-e.y)<radius)out.push(o);return out}
 const dropTypes=[['LASER','✦']];
 function startWave(next){wave=next;const base=Math.ceil((6+wave*3+Math.floor(Math.pow(wave,1.35)))*1.5),playerScale=1+Math.max(0,players.size-1)*.25,regular=Math.ceil(base*playerScale),blocks=Math.ceil(regular*4.5/20);spawnGroups=[];for(let i=0;i<blocks;i++)spawnGroups.push(...(Math.random()<.5?[4,4,4,4,4]:[5,5,5,5]));bossesToSpawn=wave===5?1:0;remainingToSpawn=spawnGroups.reduce((sum,n)=>sum+n,0)+bossesToSpawn;countdown=3;started=true;spawn=.35;$('#wave').textContent=wave;toast('Wave '+wave+' — prepare!');tone(520,.16,'triangle');setTimeout(()=>tone(760,.2,'triangle'),140)}
  function chooseEnemyType(){const available=['FOX','WOLF','EAGLE'];if(wave>=2)available.push('SNAKE');if(wave>=3)available.push('MOLE');if(wave>=4)available.push('TORNADO');if(wave>=6)available.push('ALIEN');if(wave>=7)available.push('MAGE');if(wave>=8)available.push('GHOST');if(wave>=9)available.push('PLANT');return available[Math.floor(Math.random()*available.length)]}
 function makeEnemy(type,x,y,p,now){const difficulty=1+(wave-1)*.11,speedScale=1.3*(1+Math.max(0,wave-3)*.05);let stats={type,x,y,hitAt:0,phase:Math.random()*6.28,side:Math.random()<.5?-1:1,targetId:null,nextAbility:now+2400+Math.random()*2200,nextFire:now+1800+Math.random()*1000,dashUntil:0,jumpUntil:0};if(type==='WOLF')Object.assign(stats,{hp:Math.ceil(8*difficulty),speed:34*speedScale,damage:12+Math.floor(p*.45),r:30,icon:'🐺'});else if(type==='EAGLE')Object.assign(stats,{hp:Math.ceil(3*difficulty),speed:85*speedScale,damage:3+Math.floor(p*.18),r:19,icon:'🦅'});else if(type==='SNAKE')Object.assign(stats,{hp:Math.max(1,Math.ceil(2*difficulty)),speed:125*speedScale,damage:3+Math.floor(p*.12),r:17,icon:'🐍'});else if(type==='MOLE')Object.assign(stats,{hp:Math.ceil(5*difficulty),speed:46*speedScale,damage:7+Math.floor(p*.2),r:23,icon:'🐹',burrowUntil:0});else if(type==='TORNADO')Object.assign(stats,{hp:Math.ceil(10*difficulty),speed:60*speedScale,damage:9+Math.floor(p*.3),r:29,icon:'🌪️'});else if(type==='ALIEN')Object.assign(stats,{hp:Math.ceil(5*difficulty),speed:27*speedScale,damage:5+Math.floor(p*.2),r:24,icon:'👽'});else if(type==='MAGE')Object.assign(stats,{hp:Math.ceil(6*difficulty),speed:42*speedScale,damage:7+Math.floor(p*.25),r:23,icon:'🧙'});else if(type==='GHOST')Object.assign(stats,{hp:Math.ceil(4*difficulty),speed:52*speedScale,damage:8+Math.floor(p*.25),r:25,icon:'👻'});else if(type==='PLANT')Object.assign(stats,{hp:Math.ceil(10*difficulty),speed:0,damage:5+Math.floor(p*.2),r:27,icon:'🌱'});else if(type==='FOX')Object.assign(stats,{hp:Math.ceil(3*difficulty),speed:53*speedScale,damage:5+Math.floor(p*.25),r:23,icon:'🦊'});stats.maxHp=stats.hp;return stats}
 function findHomeSpawn(radius){for(let i=0;i<48;i++){const a=Math.random()*Math.PI*2,r=220+Math.random()*130,x=world.home.x+Math.cos(a)*r,y=world.home.y+Math.sin(a)*r;if(x>radius&&y>radius&&x<world.w-radius&&y<world.h-radius&&!collidesTree(x,y,radius))return {x,y}}return findSpawnPosition(radius)}
 function makeBoss(x,y,p,now){const hp=Math.ceil(115*(1+p*.11));return {x,y,type:'BOSS',hp,maxHp:hp,speed:27*1.3*(1+Math.max(0,wave-3)*.05),damage:24+Math.floor(p*.7),r:46,icon:'👹',name:'CHUPACABRAS',hitAt:0,phase:Math.random()*6.28,side:1,targetId:null,nextAbility:now+2200,nextFire:now+1300,dashUntil:0,jumpUntil:0}}
 function spawnEnemy(){const p=wave-1,now=performance.now();if(bossesToSpawn>0||(wave>=6&&Math.random()<.08)){const {x,y}=findSpawnPosition(46);if(bossesToSpawn>0)bossesToSpawn--;else remainingToSpawn++;enemies.push(makeBoss(x,y,p,now));remainingToSpawn--;toast('CHUPACABRAS ELITE INCOMING!');tone(95,.55,'sawtooth',.065);return}let amount=spawnGroups.shift()||Math.min(4,remainingToSpawn);const type=chooseEnemyType(),center=(type==='MOLE'||type==='PLANT')?findHomeSpawn(type==='PLANT'?34:26):findSpawnPosition(28),{x,y}=center;for(let i=0;i<amount;i++){const angle=i/amount*Math.PI*2+Math.random()*.3,offset=i===0?0:58+Math.random()*46;let ex=x+Math.cos(angle)*offset,ey=y+Math.sin(angle)*offset,stats=makeEnemy(type,ex,ey,p,now);if(i>0&&collidesTree(ex,ey,stats.r)){const spot=(type==='MOLE'||type==='PLANT')?findHomeSpawn(stats.r):findSpawnPosition(stats.r);stats.x=spot.x;stats.y=spot.y}enemies.push(stats)}remainingToSpawn-=amount}
 function aimTarget(e){let best=null,bestD=780;for(const p of players.values()){if(p.hp<=0)continue;const d=Math.hypot(p.x-e.x,p.y-e.y);if(d<bestD){best=p;bestD=d}}const homeD=Math.hypot(world.home.x-e.x,world.home.y-e.y);return best&&bestD<homeD+240?{obj:best,type:'player'}:{obj:world.home,type:'farm'}}
 function dropPower(x,y,guaranteed=false){if(!guaranteed&&Math.random()>.10)return;const [type,icon]=dropTypes[Math.floor(Math.random()*dropTypes.length)];drops.push({x,y,type,icon,life:24})}
 function awardKill(e,id){if(e.scored)return;e.scored=true;const p=players.get(id);if(!p)return;const value={FOX:10,WOLF:25,EAGLE:15,SNAKE:12,MOLE:12,TORNADO:22,ALIEN:22,MAGE:24,GHOST:18,PLANT:20,BOSS:100}[e.type]||10;p.kills++;p.score+=value}
 function applyEnemyDamage(choice,damage,now){if(choice.type==='player'){const target=choice.obj;if(now>=(target.effects.INVINCIBLE||0)&&now>=(target.effects.SHIELD||0)){target.hp=Math.max(0,target.hp-damage);target.lastHit=now;tone(115,.085,'square',.035)}send(target)}else{farmHp=Math.max(0,farmHp-damage);henLastHit=now;if(now-lastHenCry>700){lastHenCry=now;henCry()}}}
 function updateEnemy(e,dt,now){let choice=aimTarget(e);const pack=nearbyEnemies(e,240);if(e.type==='WOLF'){const focused=pack.find(o=>o.type==='WOLF'&&o.targetId&&players.has(o.targetId));if(focused){const p=players.get(focused.targetId);if(p&&p.hp>0)choice={obj:p,type:'player'}}}
  let target=choice.obj,dx=target.x-e.x,dy=target.y-e.y,d=Math.hypot(dx,dy)||1;e.targetId=choice.type==='player'?target.id:null;let vx=dx/d,vy=dy/d;
  if(e.type==='BOSS'&&d<760&&now>=(e.nextFire||0)){e.nextFire=now+2600;const angle=Math.atan2(dy,dx),speed=310;fireballs.push({x:e.x+Math.cos(angle)*32,y:e.y+Math.sin(angle)*32,dx:Math.cos(angle)*speed,dy:Math.sin(angle)*speed,t:3.2,damage:14,kind:'fire'});tone(145,.24,'sawtooth',.045)}
  if(e.type==='ALIEN'&&d<670&&now>=e.nextFire){e.nextFire=now+3000;let length=d,blocked=false;for(let step=24;step<d;step+=20)if(collidesTree(e.x+vx*step,e.y+vy*step,5)){length=step;blocked=true;break}enemyBeams.push({x1:e.x+vx*20,y1:e.y+vy*20,x2:e.x+vx*length,y2:e.y+vy*length,t:.24,color:'#7cfff0'});if(!blocked)applyEnemyDamage(choice,e.damage*1.5,now);tone(780,.12,'sawtooth',.035)}
  if(e.type==='PLANT'&&d<650&&now>=e.nextFire){e.nextFire=now+1950;const angle=Math.atan2(dy,dx),speed=260;fireballs.push({x:e.x+Math.cos(angle)*28,y:e.y+Math.sin(angle)*28,dx:Math.cos(angle)*speed,dy:Math.sin(angle)*speed,t:3.1,damage:e.damage,kind:'seed'});tone(360,.07,'triangle',.025)}
  if(e.type==='MAGE'&&d>230&&now>=e.nextAbility){e.nextAbility=now+4200+Math.random()*1000;const angle=Math.random()*Math.PI*2,tx=Math.max(70,Math.min(world.w-70,target.x+Math.cos(angle)*190)),ty=Math.max(70,Math.min(world.h-70,target.y+Math.sin(angle)*190));if(!collidesTree(tx,ty,e.r)){e.x=tx;e.y=ty;e.teleportUntil=now+350;tone(540,.1,'sine',.035)}}
  if(e.type==='MOLE'&&now>=e.nextAbility){e.nextAbility=now+5100;e.burrowUntil=now+900}
  const nearby=pack.filter(o=>Math.hypot(o.x-e.x,o.y-e.y)<150).length,flank=Math.sin(now/(e.type==='TORNADO'?230:430)+e.phase)*((e.type==='TORNADO'?.48:.16)+Math.min(.5,nearby*.08))*e.side;vx+=(-dy/d)*flank;vy+=(dx/d)*flank;
  if(e.type==='FOX'&&now>e.nextAbility&&d>145){e.nextAbility=now+3800+Math.random()*3000;e.dashUntil=now+360;e.jumpUntil=e.dashUntil}if(e.type==='EAGLE'&&now>e.nextAbility&&d>140){e.nextAbility=now+4200+Math.random()*2400;e.dashUntil=now+850;e.dashX=target.x;e.dashY=target.y}
  let speed=e.speed;if(e.type==='FOX'&&now<e.dashUntil)speed*=2.55;if(e.type==='EAGLE'&&now<e.dashUntil){const ddx=e.dashX-e.x,ddy=e.dashY-e.y,dd=Math.hypot(ddx,ddy)||1;vx=ddx/dd;vy=ddy/dd;speed*=2.8}if(e.type==='TORNADO')speed*=1+Math.sin(now/170+e.phase)*.16;
  if(e.type==='PLANT')return;if(d>e.r+31&&speed>0){const dxm=vx/Math.hypot(vx,vy)*speed*dt,dym=vy/Math.hypot(vx,vy)*speed*dt;let pos;if(e.type==='GHOST'||(e.type==='MOLE'&&now<e.burrowUntil)){pos={x:Math.max(e.r,Math.min(world.w-e.r,e.x+dxm)),y:Math.max(e.r,Math.min(world.h-e.r,e.y+dym))}}else pos=moveEnemy(e,dxm,dym,e.r);e.x=pos.x;e.y=pos.y}
  else if(now-e.hitAt>780){e.hitAt=now;applyEnemyDamage(choice,e.damage,now)}
 }
 function makeShot(p,angle,laser=false){const dx=Math.cos(angle),dy=Math.sin(angle);if(!laser){shots.push({x:p.x+dx*34,y:p.y+dy*34,dx:dx*620,dy:dy*620,t:1.1,damage:1,ownerId:p.id});return}const x1=p.x+dx*34,y1=p.y+dy*34,range=500;let length=range;for(let d=20;d<=range;d+=20){if(collidesTree(x1+dx*d,y1+dy*d,5)){length=d;break}}const x2=x1+dx*length,y2=y1+dy*length,now=performance.now(),damage=p.effects.RED_LASER?3.3:3,color=p.effects.RED_LASER?'#ff5260':'#83f6ff';beams.push({x1,y1,x2,y2,t:.14,color});for(const e of enemies){if(e.hp<=0||(e.type==='MOLE'&&now<e.burrowUntil))continue;const rx=e.x-x1,ry=e.y-y1,along=Math.max(0,Math.min(length,rx*dx+ry*dy)),px=x1+dx*along,py=y1+dy*along;if(along>0&&Math.hypot(e.x-px,e.y-py)<e.r+16){e.hp-=damage;e.lastHitBy=p.id;e.hitUntil=now+100;if(e.hp<=0){awardKill(e,p.id);dropPower(e.x,e.y,e.type==='BOSS');tone(115,.14,'sawtooth',.05);setTimeout(()=>tone(70,.2,'triangle',.04),45)}else tone(210,.035,'triangle',.012)}}}
 function tick(dt,now){if(!started)return;if(countdown>0){const before=Math.ceil(countdown);countdown=Math.max(0,countdown-dt);if(countdown>0&&Math.ceil(countdown)<before)tone(440+before*75,.08,'square',.025);if(countdown===0)spawn=.35}if(countdown===0){spawn-=dt;if(remainingToSpawn>0&&spawn<=0){spawn=Math.max(.32,1.7-wave*.055);spawnEnemy()}}buildEnemyGrid();for(const e of enemies)updateEnemy(e,dt,now);
  for(const p of players.values()){if(p.hp<=0)continue;const pos=moveCircle(p,p.move.x*207*dt,p.move.y*207*dt,25);p.x=pos.x;p.y=pos.y;
   if(p.fire&&now-(p.lastShot||0)>120){p.lastShot=now;const laser=!!p.effects.LASER;makeShot(p,p.aim,laser)}
   for(const d of drops){if(!d.taken&&Math.hypot(d.x-p.x,d.y-p.y)<42){d.taken=true;const duration=d.type==='INVINCIBLE'?14000:26000;if(d.type==='LASER')p.effects.LASER=Infinity;else p.effects[d.type]=Math.max(now,p.effects[d.type]||0)+duration;if(d.type==='SHIELD'||d.type==='INVINCIBLE')toast(p.name+' picked up '+d.type);tone(d.type==='INVINCIBLE'?920:740,.18,'sine')}}send(p)}
  for(const b of shots){const ox=b.x,oy=b.y;b.x+=b.dx*dt;b.y+=b.dy*dt;b.t-=dt;if(pathBlocked(ox,oy,b.x,b.y,5)){b.t=0;continue}for(const e of enemies){if(e.hp>0&&!(e.type==='MOLE'&&now<e.burrowUntil)&&Math.hypot(e.x-b.x,e.y-b.y)<e.r+5){e.hp-=b.damage;e.lastHitBy=b.ownerId;e.hitUntil=now+100;if(e.hp<=0){awardKill(e,b.ownerId);dropPower(e.x,e.y,e.type==='BOSS');tone(125,.14,'sawtooth',.05);setTimeout(()=>tone(70,.2,'triangle',.04),45)}else tone(210,.035,'triangle',.012);if(!b.laser){b.t=0;break}}}}if(soundOn&&shots.length&&now-lastShotSound>220){tone(320,.045,'square',.018);lastShotSound=now}
  for(const b of fireballs){const ox=b.x,oy=b.y;b.x+=b.dx*dt;b.y+=b.dy*dt;b.t-=dt;if(b.x<0||b.y<0||b.x>world.w||b.y>world.h||pathBlocked(ox,oy,b.x,b.y,10)){b.t=0;continue}let hit=false;for(const p of players.values())if(p.hp>0&&Math.hypot(p.x-b.x,p.y-b.y)<32){if(now>=(p.effects.INVINCIBLE||0)&&now>=(p.effects.SHIELD||0)){p.hp=Math.max(0,p.hp-b.damage);p.lastHit=now;tone(115,.085,'square',.035)}send(p);hit=true;break}if(!hit&&Math.hypot(world.home.x-b.x,world.home.y-b.y)<125){farmHp=Math.max(0,farmHp-b.damage);henLastHit=now;if(now-lastHenCry>700){lastHenCry=now;henCry()}hit=true}if(hit)b.t=0}fireballs=fireballs.filter(b=>b.t>0);
  shots=shots.filter(b=>b.t>0);beams=beams.filter(b=>((b.t-=dt)>0));enemyBeams=enemyBeams.filter(b=>((b.t-=dt)>0));enemies=enemies.filter(e=>e.hp>0);drops=drops.filter(d=>!d.taken&&((d.life-=dt)>0));if(farmHp<=0&&!gameOver){started=false;gameOver=true;countdown=0;$('#startBtn').disabled=true;saveRun();for(const p of players.values())send(p)}else if(remainingToSpawn===0&&enemies.length===0&&wave>0&&countdown===0){farmHp=Math.min(100,farmHp+8);startWave(wave+1)}$('#farmHp').textContent=Math.ceil(farmHp)+'%';$('#enemyCount').textContent=remainingToSpawn+enemies.length;
 }
 function buildStaticMap(){const surface=document.createElement('canvas');surface.width=world.w;surface.height=world.h;const m=surface.getContext('2d');
m.fillStyle='#8acb67';m.fillRect(0,0,world.w,world.h);const floorPattern=m.createPattern(floorTile,'repeat');if(floorPattern){m.save();m.globalAlpha=.22;m.fillStyle=floorPattern;m.fillRect(0,0,world.w,world.h);m.restore()}m.strokeStyle='#d8c480';m.lineWidth=48;m.setLineDash([36,26]);m.strokeRect(40,40,world.w-80,world.h-80);m.setLineDash([]);
  m.fillStyle='#b99a65';roundedPath(860,0,80,world.h,32,m);m.fill();roundedPath(0,610,world.w,75,32,m);m.fill();if(soilSprite.complete&&soilSprite.naturalWidth){m.save();m.beginPath();roundedPath(860,0,80,world.h,32,m);roundedPath(0,610,world.w,75,32,m);m.clip();m.globalAlpha=.24;for(let x=-65;x<world.w;x+=95)m.drawImage(soilSprite,x,585,130,130);for(let y=-65;y<world.h;y+=95){m.save();m.translate(900,y+65);m.rotate(Math.PI/2);m.drawImage(soilSprite,-65,-65,130,130);m.restore()}m.restore()}for(let i=0;i<10;i++){m.fillStyle=i%2?'#e4bc5c':'#6f9c42';m.fillRect(175+i%5*65,185+Math.floor(i/5)*90,45,58)}for(const g of grassTufts){if(grassClump.complete&&grassClump.naturalWidth){m.save();m.translate(g.x,g.y);m.rotate(g.r);m.drawImage(grassClump,-g.s/2,-g.s*.84,g.s,g.s);m.restore()}else{m.strokeStyle='#4d873e';m.lineWidth=4;m.beginPath();m.moveTo(g.x,g.y);m.lineTo(g.x-7,g.y-20);m.moveTo(g.x,g.y);m.lineTo(g.x+4,g.y-26);m.moveTo(g.x,g.y);m.lineTo(g.x+11,g.y-18);m.stroke()}}
  for(const t of trees){m.fillStyle='#35573b55';m.beginPath();m.ellipse(t.x,t.y,t.s*.95,t.s*.5,0,0,7);m.fill();if(natureAtlas.complete&&natureAtlas.naturalWidth){const size=t.s*3.3,sx=(t.model%4)*256,sy=Math.floor(t.model/4)*256;m.drawImage(natureAtlas,sx,sy,256,256,t.x-size/2,t.y-size*.92,size,size)}else{m.font=`${Math.round(t.s*2)}px system-ui`;m.textAlign='center';m.textBaseline='bottom';m.fillText('🌳',t.x,t.y)}}
 return surface}
 function draw(now){const dt=Math.min(.05,(now-last)/1000);last=now;tick(dt,now);const w=canvas.width,h=canvas.height,sx=w/devicePixelRatio,sy=h/devicePixelRatio,viewH=sy-70;let minX=world.home.x,maxX=minX,minY=world.home.y,maxY=minY;for(const p of players.values())if(p.hp>0){minX=Math.min(minX,p.x);maxX=Math.max(maxX,p.x);minY=Math.min(minY,p.y);maxY=Math.max(maxY,p.y)}const margin=185,minScale=Math.min(sx/(world.w+80),viewH/(world.h*.82+80)),targetScale=Math.max(minScale,Math.min(1.05,Math.min(sx/(maxX-minX+margin*2),viewH/((maxY-minY+margin*2)*.82)))),targetX=(minX+maxX)/2,targetY=(minY+maxY)/2,blend=Math.min(1,dt*2.8);camera.scale+=(targetScale-camera.scale)*blend;camera.x+=(targetX-camera.x)*blend;camera.y+=(targetY-camera.y)*blend;const scale=camera.scale,center=camera;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.fillStyle='#77b85f';ctx.fillRect(0,0,sx,sy);ctx.save();ctx.translate(sx/2,(sy+70)/2);ctx.scale(scale,scale);ctx.transform(1,0,0,.82,0,0);ctx.translate(-center.x,-center.y);if(mapScene)ctx.drawImage(mapScene,0,0);else{ctx.fillStyle='#8acb67';ctx.fillRect(0,0,world.w,world.h)}
  const hme=world.home,henFlash=henLastHit>0&&now-henLastHit<500&&Math.floor(now/70)%2===0;if(shackSprite.complete&&shackSprite.naturalWidth){ctx.fillStyle='#35573b66';ctx.beginPath();ctx.ellipse(hme.x,hme.y+17.5,80,35,0,0,7);ctx.fill();ctx.drawImage(shackSprite,hme.x-80,hme.y-62.5,160,120);ctx.fillStyle='#99613a';ctx.strokeStyle='#68412d';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(hme.x-71,hme.y-43);ctx.lineTo(hme.x,hme.y-94);ctx.lineTo(hme.x+71,hme.y-43);ctx.closePath();ctx.fill();ctx.stroke();ctx.strokeStyle='#d19859';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(hme.x-47.5,hme.y-57);ctx.lineTo(hme.x,hme.y-90.5);ctx.lineTo(hme.x+47.5,hme.y-57);ctx.stroke();ctx.fillStyle='#543b2b';ctx.fillRect(hme.x-11.5,hme.y+13.5,23,28.5)}else{ctx.fillStyle='#8a5735';ctx.fillRect(hme.x-65,hme.y-37.5,130,90);ctx.fillStyle='#ba4834';ctx.beginPath();ctx.moveTo(hme.x-80,hme.y-35);ctx.lineTo(hme.x,hme.y-100);ctx.lineTo(hme.x+80,hme.y-35);ctx.fill()}uprightAt(hme.x,hme.y-52.5,()=>{ctx.fillStyle='#f8de83';ctx.font='bold 26px system-ui';ctx.textAlign='center';ctx.fillText('HEN HOUSE',0,0)});ctx.fillStyle='#fff1bd';ctx.beginPath();ctx.arc(hme.x,hme.y+32.5,16.5,0,7);ctx.fill();if(eggSprite.complete&&eggSprite.naturalWidth){for(const [ex,ey,es] of [[hme.x-30,hme.y+59,17],[hme.x,hme.y+62,19],[hme.x+30,hme.y+59,17]])ctx.drawImage(eggSprite,ex-es/2,ey-es,es,es)}else{ctx.fillStyle='#f1c83f';ctx.beginPath();ctx.arc(hme.x-30,hme.y+60,8,0,7);ctx.arc(hme.x,hme.y+62.5,8,0,7);ctx.arc(hme.x+30,hme.y+60,8,0,7);ctx.fill()}if(henFlash){uprightAt(hme.x,hme.y+47.5,()=>{ctx.fillStyle='#ff263dcc';ctx.beginPath();ctx.arc(0,-6,15,0,7);ctx.fill()})}if(actorSprites.mama.complete&&actorSprites.mama.naturalWidth){ctx.save();if(henFlash&&Math.floor(now/70)%2===0)ctx.globalAlpha=.45;ctx.drawImage(actorSprites.mama,hme.x-28,hme.y+10,56,56);ctx.restore()}else uprightAt(hme.x,hme.y+47.5,()=>{ctx.font='48px system-ui';ctx.textAlign='center';ctx.fillText('🐔',0,0)});
  uprightAt(hme.x,hme.y-137.5,()=>{ctx.fillStyle='#18372b';ctx.fillRect(-165,-10,330,24);ctx.fillStyle=henFlash?'#ff3947':'#52d57b';ctx.fillRect(-160,-5,320*Math.max(0,farmHp)/100,14);ctx.strokeStyle='#fff2c4';ctx.lineWidth=3;ctx.strokeRect(-165,-10,330,24);ctx.fillStyle='#fff7db';ctx.font='bold 20px system-ui';ctx.textAlign='center';ctx.fillText('MAMA HEN · '+Math.ceil(farmHp)+'%',0,-20)});
  for(const b of fireballs){ctx.save();ctx.fillStyle=b.kind==='seed'?'#b8ed53':'#ff552d';ctx.shadowColor=b.kind==='seed'?'#b8ed53':'#ff2600';ctx.shadowBlur=22;ctx.beginPath();ctx.arc(b.x,b.y,13+Math.sin(now/45)*3,0,7);ctx.fill();ctx.fillStyle=b.kind==='seed'?'#f6ffd5':'#ffe985';ctx.beginPath();ctx.arc(b.x,b.y,6,0,7);ctx.fill();ctx.restore()}for(const e of enemies){const jump=e.type==='FOX'&&now<e.jumpUntil?Math.sin((e.jumpUntil-now)/360*Math.PI)*32:0;ctx.fillStyle='#35573b66';ctx.beginPath();ctx.ellipse(e.x,e.y,e.r*1.35,e.r*.65,0,0,7);ctx.fill();const sprite=actorSprites[e.type],spriteSize=e.type==='BOSS'?e.r*3.4:e.type==='EAGLE'?e.r*3.2:e.type==='TORNADO'?e.r*2.9:e.type==='SNAKE'?e.r*2.5:e.r*2.7;ctx.save();if(now<(e.hitUntil||0))ctx.globalAlpha=.58;if(e.type==='MOLE'&&now<e.burrowUntil)ctx.globalAlpha=.26; if(sprite&&sprite.complete&&sprite.naturalWidth){if(e.type==='TORNADO'){ctx.translate(e.x,e.y-jump);ctx.rotate(now/150);ctx.drawImage(sprite,-spriteSize/2,-spriteSize*.72,spriteSize,spriteSize)}else ctx.drawImage(sprite,e.x-spriteSize/2,e.y-jump-spriteSize*.72,spriteSize,spriteSize)}else{ctx.fillStyle=e.type==='BOSS'?'#772b37':e.type==='WOLF'?'#65645b':e.type==='EAGLE'?'#b16c45':e.type==='SNAKE'?'#4e9c53':'#d17a35';ctx.beginPath();ctx.ellipse(e.x,e.y-jump,e.r*1.1,e.r*.9,0,0,7);ctx.fill();uprightAt(e.x,e.y-jump,()=>{ctx.font=`${e.type==='BOSS'?78:e.type==='SNAKE'?34:40}px system-ui`;ctx.textAlign='center';ctx.fillText(e.icon,0,0)})}ctx.restore();if(e.type==='MAGE'&&now<(e.teleportUntil||0)){ctx.strokeStyle='#db9cff';ctx.lineWidth=5;ctx.beginPath();ctx.arc(e.x,e.y,38+(e.teleportUntil-now)*.03,0,7);ctx.stroke()}if(e.type==='BOSS'){ctx.strokeStyle='#ff5b61';ctx.lineWidth=6;ctx.beginPath();ctx.ellipse(e.x,e.y,e.r*1.28,e.r*1.12,0,0,7);ctx.stroke()}uprightAt(e.x,e.y-jump,()=>{ctx.fillStyle='#263d30';ctx.fillRect(-e.r,-e.r-9,e.r*2,5);ctx.fillStyle='#ef4b50';ctx.fillRect(-e.r,-e.r-9,e.r*2*Math.max(0,e.hp/e.maxHp),5);if(e.type==='BOSS'){ctx.fillStyle='#ffe4a0';ctx.font='bold 15px system-ui';ctx.fillText('CHUPACABRAS',0,-e.r-16)}});if(e.type==='EAGLE'&&now<e.dashUntil){ctx.strokeStyle='#f8f3b3';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(e.x,e.y);ctx.lineTo(e.dashX,e.dashY);ctx.stroke()}}for(const d of drops){uprightAt(d.x,d.y,()=>{ctx.font='30px system-ui';ctx.textAlign='center';ctx.fillText(d.icon,0,0)});ctx.strokeStyle='#fff8';ctx.beginPath();ctx.arc(d.x,d.y,25+Math.sin(now/120)*3,0,7);ctx.stroke()}
  for(const p of players.values()){const playerFlash=p.lastHit>0&&now-p.lastHit<450&&Math.floor(now/65)%2===0;ctx.fillStyle='#35573b66';ctx.beginPath();ctx.ellipse(p.x,p.y,35,15,0,0,7);ctx.fill();ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.aim);ctx.strokeStyle='#463c27';ctx.lineWidth=9;ctx.beginPath();ctx.moveTo(5,0);ctx.lineTo(43,0);ctx.stroke();ctx.restore();if(playerFlash){ctx.fillStyle='#f32636cc';ctx.beginPath();ctx.ellipse(p.x,p.y,31,27,0,0,7);ctx.fill();ctx.strokeStyle='#ffbac0';ctx.lineWidth=4;ctx.stroke()}const playerSprite=actorSprites.player;if(playerSprite.complete&&playerSprite.naturalWidth){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.aim);ctx.drawImage(playerSprite,-31,-39,62,62);ctx.restore()}else{ctx.fillStyle=p.color;ctx.beginPath();ctx.ellipse(p.x,p.y,28,24,0,0,7);ctx.fill()}if(now<(p.effects.INVINCIBLE||0)||now<(p.effects.SHIELD||0)){ctx.strokeStyle=now<(p.effects.SHIELD||0)?'#8ceaff':'#ffe86a';ctx.lineWidth=5;ctx.beginPath();ctx.arc(p.x,p.y,37,0,7);ctx.stroke()}if(p.hp<=0)uprightAt(p.x,p.y+10,()=>{ctx.font='30px system-ui';ctx.textAlign='center';ctx.fillText('💫',0,0)});uprightAt(p.x,p.y-43,()=>{ctx.fillStyle='#173029';ctx.font='bold 16px system-ui';ctx.textAlign='center';ctx.fillText(p.name+' · '+p.score,0,0);ctx.fillStyle='#263d30';ctx.fillRect(-25,6,50,5);ctx.fillStyle='#ff7570';ctx.fillRect(-25,6,50*Math.max(0,p.hp)/100,5);const active=Object.keys(p.effects).filter(k=>(k==='SHIELD'||k==='INVINCIBLE')&&now<p.effects[k]);if(active.length){ctx.fillStyle='#173029';ctx.fillText(active.join(' + '),0,29)}})}
  for(const beam of enemyBeams){ctx.save();ctx.globalAlpha=Math.min(1,beam.t/.24);ctx.strokeStyle=beam.color;ctx.lineWidth=14;ctx.shadowColor=beam.color;ctx.shadowBlur=18;ctx.beginPath();ctx.moveTo(beam.x1,beam.y1);ctx.lineTo(beam.x2,beam.y2);ctx.stroke();ctx.restore()}for(const beam of beams){ctx.save();ctx.globalAlpha=Math.min(1,beam.t/.14);ctx.strokeStyle=beam.color||'#83f6ff';ctx.lineWidth=16;ctx.shadowColor=beam.color||'#37eaff';ctx.shadowBlur=22;ctx.beginPath();ctx.moveTo(beam.x1,beam.y1);ctx.lineTo(beam.x2,beam.y2);ctx.stroke();ctx.strokeStyle='#efffff';ctx.lineWidth=5;ctx.shadowBlur=0;ctx.stroke();ctx.restore()}for(const b of shots){ctx.fillStyle='#fff1a2';ctx.beginPath();ctx.arc(b.x,b.y,7,0,7);ctx.fill()}ctx.restore();if(countdown>0){const cx=sx/2,cy=(sy+70)/2;ctx.save();ctx.fillStyle='#10251de8';ctx.strokeStyle='#ffe17a';ctx.lineWidth=3;roundedPath(cx-130,cy-102,260,204,24);ctx.fill();ctx.stroke();ctx.fillStyle='#f9dfa0';ctx.textAlign='center';ctx.font='900 20px system-ui';ctx.fillText('WAVE '+wave, cx,cy-58);ctx.fillStyle='#fff';ctx.font='1000 90px system-ui';ctx.fillText(String(Math.ceil(countdown)),cx,cy+34);ctx.fillStyle='#d9e9d5';ctx.font='bold 14px system-ui';ctx.fillText('GET READY',cx,cy+72);ctx.restore()}$('#wave').textContent=wave;requestAnimationFrame(draw);
}
requestAnimationFrame(draw);
}
function initController(roomId){
 const status=$('#joinStatus'),connStatus=$('#connection');let peer,conn,move={x:0,y:0},aim=0,fire=false,joined=false;
 peer=new Peer(undefined,{debug:0});peer.on('open',()=>{conn=peer.connect(roomId,{reliable:true});conn.on('open',()=>{connStatus.textContent='CONNECTED';status.textContent='Connected to the farm.'});conn.on('data',d=>{if(d.type==='state'&&d.started&&joined)status.textContent='Defend the farm!' });conn.on('close',()=>{connStatus.textContent='DISCONNECTED';status.textContent='Host connection ended.'})});peer.on('error',e=>{connStatus.textContent='OFFLINE';status.textContent='Could not connect ('+e.type+'). Check the host lobby.'});
 $('#joinBtn').onclick=()=>{if(!conn||!conn.open){status.textContent='Still connecting to the host…';return}conn.send({type:'join',name:$('#playerName').value.trim()||'CHICK'});joined=true;$('#joinPanel').classList.add('hidden');$('#controls').classList.remove('hidden')};
 function setupStick(zone,kind){const base=zone.querySelector('.stick-base'),knob=zone.querySelector('.stick-knob');let pointer=null;function set(e){const r=base.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),limit=r.width*.34,d=Math.hypot(dx,dy),k=d>limit?limit/d:1,nx=dx*k,ny=dy*k;knob.style.transform=`translate(${nx}px,${ny}px)`;const mag=Math.hypot(nx,ny)/limit,dead=.16;if(kind==='move'){if(mag<dead)move={x:0,y:0};else{const q=(mag-dead)/(1-dead);move={x:nx/d*q,y:ny/d*q}}}else{if(mag>=dead)aim=Math.atan2(ny,nx);fire=mag>=dead}}
  zone.addEventListener('pointerdown',e=>{if(pointer!==null)return;pointer=e.pointerId;zone.setPointerCapture(pointer);set(e);e.preventDefault()});zone.addEventListener('pointermove',e=>{if(e.pointerId===pointer)set(e)});function up(e){if(e.pointerId!==pointer)return;pointer=null;knob.style.transform='translate(0,0)';if(kind==='move')move={x:0,y:0};else fire=false}zone.addEventListener('pointerup',up);zone.addEventListener('pointercancel',up)}
 setupStick($('#moveZone'),'move');setupStick($('#aimZone'),'aim');
 const fireBtn=$('#fire');fireBtn.classList.add('hidden');
 const keys=new Set();addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();keys.add(k);if(k===' ')fire=true});addEventListener('keyup',e=>{const k=e.key.toLowerCase();keys.delete(k);if(k===' ')fire=false});addEventListener('blur',()=>{keys.clear();fire=false});addEventListener('mousemove',e=>{if(joined)aim=Math.atan2(e.clientY-innerHeight/2,e.clientX-innerWidth/2)});addEventListener('mousedown',e=>{if(joined&&e.button===0)fire=true});addEventListener('mouseup',e=>{if(e.button===0)fire=false});
 setInterval(()=>{const x=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),y=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0),m=Math.hypot(x,y);if(m)move={x:x/m,y:y/m};if(conn?.open&&joined)conn.send({type:'input',move,aim,fire})},50);
}
})();
