(()=>{'use strict';
const $=s=>document.querySelector(s), params=new URLSearchParams(location.search), hostMode=params.get('host')==='1', room=params.get('room');
const host=$('#host'),ctrl=$('#controller'),landing=$('#landing');
if(hostMode){host.classList.remove('hidden');initHost()}else if(room){ctrl.classList.remove('hidden');initController(room)}else landing.classList.remove('hidden');
function initHost(){
 const c=$('#game'),ctx=c.getContext('2d'), lobby=$('#lobby'),roster=$('#roster'), peers=new Map(),players=new Map();let peer=null,started=false,wave=0,hp=100,shots=[],enemies=[],last=performance.now(),spawn=0;
 const world={w:3600,h:2400,home:{x:1800,y:1300}};
 const trees=[];for(let i=0;i<32;i++){let a=(i*2.399),r=760+(i%5)*185;trees.push({x:world.home.x+Math.cos(a)*r,y:world.home.y+Math.sin(a)*r,s:30+(i*17%25)})}for(let i=0;i<20;i++)trees.push({x:150+(i*719%3300),y:150+(i*431%2100),s:24+(i*13%27)});
 function resize(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio}addEventListener('resize',resize);resize();
 function send(p){try{p.conn.send({type:'state',self:p.id,x:p.x,y:p.y,aim:p.aim,alive:true,started})}catch{}}
 function rosterUpdate(){ $('#playerCount').textContent=players.size;roster.innerHTML='';for(const p of players.values()){const e=document.createElement('span');e.textContent='🐥 '+p.name;roster.append(e)} }
 function addPlayer(conn,msg){if(!msg||msg.type!=='join')return;const id=conn.peer;if(players.has(id))return;const n=players.size;const p={id,name:String(msg.name||'CHICK').slice(0,12),x:world.home.x-150+(n%4)*100,y:world.home.y+180+Math.floor(n/4)*75,aim:0,move:{x:0,y:0},fire:false,conn,color:['#ffe05e','#f48caa','#82c9ff','#bd9aff','#77df98','#ffad59'][n%6]};players.set(id,p);peers.set(id,conn);rosterUpdate();conn.on('data',d=>{if(d.type==='input'){p.move=d.move||p.move;p.aim=d.aim??p.aim;p.fire=!!d.fire}});conn.on('close',()=>{players.delete(id);peers.delete(id);rosterUpdate()});send(p); }
 peer= new Peer(undefined,{debug:0});peer.on('open',id=>{const url=new URL(location.href);url.search='?room='+encodeURIComponent(id);$('#roomCode').textContent=id;$('#joinUrl').textContent=url.href;$('#qr').src='https://api.qrserver.com/v1/create-qr-code/?size=180x180&data='+encodeURIComponent(url.href)});peer.on('connection',conn=>{conn.on('data',d=>{if(d.type==='join')addPlayer(conn,d)})});peer.on('error',e=>toast('Connection service: '+e.type));
 $('#startBtn').onclick=()=>{if(started)return;started=true;lobby.classList.add('hidden');wave=1;$('#wave').textContent=wave;toast('Wave 1 — defend the farm!')};
 function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
 function spawnEnemy(){let side=Math.floor(Math.random()*4),x=side===0?80:side===1?world.w-80:Math.random()*world.w,y=side===2?80:side===3?world.h-80:Math.random()*world.h;enemies.push({x,y,hp:1,speed:36+Math.random()*15})}
 function draw(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(started){spawn-=dt;if(spawn<=0){spawn=1.7;spawnEnemy()}for(const e of enemies){const target=world.home,dx=target.x-e.x,dy=target.y-e.y,d=Math.hypot(dx,dy)||1;e.x+=dx/d*e.speed*dt;e.y+=dy/d*e.speed*dt;if(d<100){e.hp=0;hp=Math.max(0,hp-.8)}}for(const p of players.values()){p.x=Math.max(80,Math.min(world.w-80,p.x+p.move.x*180*dt));p.y=Math.max(80,Math.min(world.h-80,p.y+p.move.y*180*dt));if(p.fire&&Math.random()<.26)shots.push({x:p.x+Math.cos(p.aim)*25,y:p.y+Math.sin(p.aim)*25,dx:Math.cos(p.aim)*620,dy:Math.sin(p.aim)*620,t:1.1});send(p)}for(const b of shots){b.x+=b.dx*dt;b.y+=b.dy*dt;b.t-=dt;for(const e of enemies)if(e.hp>0&&Math.hypot(e.x-b.x,e.y-b.y)<28){e.hp=0;b.t=0;break}}shots=shots.filter(b=>b.t>0);enemies=enemies.filter(e=>e.hp>0);if(hp<=0){started=false;toast('The farm needs defending — press START GAME to begin again.')}$('#farmHp').textContent=Math.ceil(hp)+'%'}
  const w=c.width,h=c.height,sx=w/devicePixelRatio,sy=h/devicePixelRatio,scale=Math.min(sx/1850,sy/1200,1.15),center=world.home;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.fillStyle='#77b85f';ctx.fillRect(0,0,sx,sy);ctx.save();ctx.translate(sx/2-center.x*scale,sy/2-center.y*scale);ctx.scale(scale,scale);
  ctx.fillStyle='#8acb67';ctx.fillRect(0,0,world.w,world.h);ctx.strokeStyle='#d8c480';ctx.lineWidth=95;ctx.setLineDash([36,26]);ctx.strokeRect(80,80,world.w-160,world.h-160);ctx.setLineDash([]);
  // farm paths, fields and obstacles arranged around the central defense
  ctx.fillStyle='#c8a76a';ctx.beginPath();ctx.roundRect(1720,0,160,world.h,65);ctx.roundRect(0,1220,world.w,150,65);ctx.fill();
  for(let i=0;i<10;i++){ctx.fillStyle=i%2?'#e4bc5c':'#6f9c42';ctx.fillRect(350+i%5*130,370+Math.floor(i/5)*180,90,115)}
  for(const t of trees){ctx.fillStyle='#704c34';ctx.fillRect(t.x-7,t.y,14,t.s);ctx.fillStyle='#236a3b';ctx.beginPath();ctx.arc(t.x,t.y,t.s,0,Math.PI*2);ctx.fill();ctx.fillStyle='#398d47';ctx.beginPath();ctx.arc(t.x-7,t.y-6,t.s*.67,0,Math.PI*2);ctx.fill()}
  ctx.fillStyle='#8a5735';ctx.fillRect(center.x-130,center.y-75,260,180);ctx.fillStyle='#ba4834';ctx.beginPath();ctx.moveTo(center.x-160,center.y-70);ctx.lineTo(center.x,center.y-200);ctx.lineTo(center.x+160,center.y-70);ctx.fill();ctx.fillStyle='#f8de83';ctx.font='bold 26px system-ui';ctx.textAlign='center';ctx.fillText('HEN HOUSE',center.x,center.y-95);
  ctx.fillStyle='#fff1bd';ctx.beginPath();ctx.arc(center.x,center.y+65,33,0,7);ctx.fill();ctx.fillStyle='#f1c83f';ctx.beginPath();ctx.arc(center.x-60,center.y+120,16,0,7);ctx.arc(center.x,center.y+125,16,0,7);ctx.arc(center.x+60,center.y+120,16,0,7);ctx.fill();ctx.font='48px system-ui';ctx.fillText('🐔',center.x,center.y+95);
  for(const e of enemies){ctx.font='40px system-ui';ctx.fillText('🦊',e.x,e.y);}
  for(const p of players.values()){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.aim);ctx.strokeStyle='#463c27';ctx.lineWidth=9;ctx.beginPath();ctx.moveTo(5,0);ctx.lineTo(43,0);ctx.stroke();ctx.restore();ctx.fillStyle=p.color;ctx.beginPath();ctx.ellipse(p.x,p.y,28,24,0,0,7);ctx.fill();ctx.font='30px system-ui';ctx.textAlign='center';ctx.fillText('🐥',p.x,p.y+10);ctx.fillStyle='#173029';ctx.font='bold 16px system-ui';ctx.fillText(p.name,p.x,p.y-38)}
  for(const b of shots){ctx.fillStyle='#fff1a2';ctx.beginPath();ctx.arc(b.x,b.y,7,0,7);ctx.fill()}ctx.restore();$('#wave').textContent=wave;requestAnimationFrame(draw)}requestAnimationFrame(draw);
}
function initController(roomId){
 const status=$('#joinStatus'),connStatus=$('#connection');let peer=null,conn=null,move={x:0,y:0},aim=0,fire=false,hasAim=false,joined=false;peer=new Peer(undefined,{debug:0});peer.on('open',()=>{conn=peer.connect(roomId,{reliable:true});conn.on('open',()=>{connStatus.textContent='CONNECTED';status.textContent='Connected to the farm.'});conn.on('data',d=>{if(d.type==='state'){if(d.started&&joined)status.textContent='Defend the farm!';else if(!joined)status.textContent='Enter your name and join.'}});conn.on('close',()=>{connStatus.textContent='DISCONNECTED';status.textContent='Host connection ended.'})});peer.on('error',e=>{connStatus.textContent='OFFLINE';status.textContent='Could not connect ('+e.type+'). Check the host lobby.'});
 $('#joinBtn').onclick=()=>{if(!conn||!conn.open){status.textContent='Still connecting to the host…';return}const name=$('#playerName').value.trim()||'CHICK';conn.send({type:'join',name});joined=true;$('#joinPanel').classList.add('hidden');$('#controls').classList.remove('hidden')};
 function setupStick(zone,kind){const base=zone.querySelector('.stick-base'),knob=zone.querySelector('.stick-knob');let pointer=null;function set(e){const r=base.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,limit=r.width*.34,dx=e.clientX-cx,dy=e.clientY-cy,d=Math.hypot(dx,dy),k=d>limit?limit/d:1,nx=dx*k,ny=dy*k;knob.style.transform=`translate(${nx}px,${ny}px)`;const mag=Math.hypot(nx,ny)/limit,dead=.16;if(kind==='move'){if(mag<dead)move={x:0,y:0};else{const q=(mag-dead)/(1-dead);move={x:nx/d* q,y:ny/d*q}}}else if(mag>=dead){aim=Math.atan2(ny,nx);hasAim=true}}
 zone.addEventListener('pointerdown',e=>{if(pointer!==null)return;pointer=e.pointerId;zone.setPointerCapture(pointer);set(e);e.preventDefault()});zone.addEventListener('pointermove',e=>{if(e.pointerId===pointer)set(e)});function up(e){if(e.pointerId!==pointer)return;pointer=null;knob.style.transform='translate(0,0)';if(kind==='move')move={x:0,y:0}}zone.addEventListener('pointerup',up);zone.addEventListener('pointercancel',up)}
 setupStick($('#moveZone'),'move');setupStick($('#aimZone'),'aim');const fireBtn=$('#fire');fireBtn.addEventListener('pointerdown',e=>{fire=true;fireBtn.setPointerCapture(e.pointerId);e.preventDefault()});fireBtn.addEventListener('pointerup',()=>fire=false);fireBtn.addEventListener('pointercancel',()=>fire=false);
 const keys=new Set();addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();keys.add(k);if(k===' ')fire=true});addEventListener('keyup',e=>{const k=e.key.toLowerCase();keys.delete(k);if(k===' ')fire=false});addEventListener('blur',()=>{keys.clear();fire=false});addEventListener('mousemove',e=>{if(!joined)return;const dx=e.clientX-innerWidth/2,dy=e.clientY-innerHeight/2;if(Math.hypot(dx,dy)>8){aim=Math.atan2(dy,dx);hasAim=true}});addEventListener('mousedown',e=>{if(joined&&e.button===0)fire=true});addEventListener('mouseup',e=>{if(e.button===0)fire=false});
 function keyboard(){const x=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),y=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0),m=Math.hypot(x,y);if(m)move={x:x/m,y:y/m}}
 setInterval(()=>{keyboard();if(conn?.open&&joined)conn.send({type:'input',move,aim,hasAim,fire})},50);
}
})();
